#Application
spring:
  application:
    name: fix-client-example
  main:
    web-application-type: reactive

#Quickfixj
quickfixj:
  jmx-enabled: true
  #startup-timeout: 20s
  config: "classpath:quickfixj.cfg"
  dictionary: "classpath:FIX43.xml"

management:
  #Health/Actuator endpoints
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          amber: 503 #on amber (quickfixj state) return service unavailable
        order: DOWN, OUT_OF_SERVICE, AMBER, UP, UNKNOWN
    quickfixj.enabled: true
  #Metrics
  metrics.export:
    #Simple In memory (maybe later integrate with graphite or prometheus?)
    simple.enabled: true
    #JMX
    #jmx.domain: ch.voulgarakis.fix.example

#Logging
logging:
  #Enabled log4j transfer of MDC (id) for subscriber to publisher
  rxMDC: true
  #the logging patterns
  pattern:
    console: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%X{id}]){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}